# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [5]:
# Create a 1-dimensional NumPy array using np.array()

one_d_array = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()

two_d_array = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()

three_d_array = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                          [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

one_d_array, two_d_array, three_d_array



(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [9]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

one_d_array.shape, one_d_array.ndim, one_d_array.dtype, one_d_array.size, type(one_d_array)


((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array

two_d_array.shape, two_d_array.ndim, two_d_array.dtype, two_d_array.size, type(two_d_array)


In [5]:
# Attributes of 3-dimensional array

three_d_array.shape, three_d_array.ndim, three_d_array.dtype, three_d_array.size, type(three_d_array)


In [10]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd

two_d_df = pd.DataFrame(two_d_array)
two_d_df

0  1  2
0  1  2  3
1  4  5  6

In [11]:
# Create an array of shape (10, 2) with only ones

ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros

zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3

random_array = np.arange(0, 100, 3)
random_array


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)

random_int_array = np.random.randint(0, 10, size=(7, 2))
random_int_array


array([[4, 5],
       [7, 1],
       [6, 7],
       [6, 2],
       [3, 5],
       [0, 1],
       [7, 4]])

In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)

random_float_array = np.random.random((3, 5))
random_float_array


array([[0.99689263, 0.5391377 , 0.69102664, 0.42251676, 0.42248477],
       [0.11794675, 0.41804708, 0.12242454, 0.8598578 , 0.2721223 ],
       [0.54404947, 0.15474464, 0.83884576, 0.41654472, 0.88134074]])

In [19]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)

random_int_array_1 = np.random.randint(0, 10, size=(4, 6))
random_int_array_1


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

***Answer:*** Numbers won't change. Same outcome cna be ensured, as Python (and NumPy) can only generate pseudo-random numbers.


In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

random_int_array_2 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created

random_int_array_2, np.unique(random_int_array_2)


(array([[9, 7, 9, 8, 2, 1, 7],
        [7, 8, 5, 3, 8, 6, 3],
        [1, 3, 5, 3, 1, 5, 7]]),
 array([1, 2, 3, 5, 6, 7, 8, 9]))

In [24]:
# Find the 0'th index of the latest array you created

random_int_array_2[0]


array([9, 7, 9, 8, 2, 1, 7])

In [25]:
# Get the first 2 rows of latest array you created

random_int_array_2[:2]


array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [27]:
# Get the first 2 values of the first 2 rows of the latest array

random_int_array_2[:2, :2]

array([[9, 7],
       [7, 8]])

In [30]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

random_array = np.random.randint(0, 10, size=(3, 5))
ones = np.ones((3, 5))

random_array, ones



(array([[5, 1, 9, 8, 4],
        [5, 3, 9, 6, 8],
        [6, 0, 0, 8, 8]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [31]:
# Add the two arrays together

random_array + ones


array([[ 6.,  2., 10.,  9.,  5.],
       [ 6.,  4., 10.,  7.,  9.],
       [ 7.,  1.,  1.,  9.,  9.]])

In [32]:
# Create another array of ones of shape (5, 3)

ones_1 = np.ones((5, 3))



In [34]:
# Try add the array of ones and the other most recent array together

random_array + ones_1


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

***Answer:*** The two arrays have diffferent shape.

How would you fix it?

***Answer:*** Reshape or in this case transpose one of the arrays.


In [36]:
# Create another array of ones of shape (3, 5)

ones_2 = np.ones((3, 5))


In [37]:
# Subtract the new array of ones from the other most recent array

random_array - ones_2


array([[ 4.,  0.,  8.,  7.,  3.],
       [ 4.,  2.,  8.,  5.,  7.],
       [ 5., -1., -1.,  7.,  7.]])

In [38]:
# Multiply the ones array with the latest array

random_array * ones_2


array([[5., 1., 9., 8., 4.],
       [5., 3., 9., 6., 8.],
       [6., 0., 0., 8., 8.]])

In [39]:
# Take the latest array to the power of 2 using '**'

random_array ** 2


array([[25,  1, 81, 64, 16],
       [25,  9, 81, 36, 64],
       [36,  0,  0, 64, 64]])

In [40]:
# Do the same thing with np.square()

np.square(random_array)


array([[25,  1, 81, 64, 16],
       [25,  9, 81, 36, 64],
       [36,  0,  0, 64, 64]])

In [41]:
# Find the mean of the latest array using np.mean()

np.mean(random_array)


5.333333333333333

In [43]:
# Find the maximum of the latest array using np.max()

np.max(random_array)


9

In [44]:
# Find the minimum of the latest array using np.min()

np.min(random_array)


0

In [71]:
# Find the standard deviation of the latest array

np.std(random_array)


3.0477678535099892

In [72]:
# Find the variance of the latest array

np.var(random_array)



9.288888888888888

In [50]:
# Reshape the latest array to (3, 5, 1)

random_array.reshape((3, 5, 1))


array([[[5],
        [1],
        [9],
        [8],
        [4]],

       [[5],
        [3],
        [9],
        [6],
        [8]],

       [[6],
        [0],
        [0],
        [8],
        [8]]])

In [51]:
# Transpose the latest array

random_array.T


array([[5, 5, 6],
       [1, 3, 0],
       [9, 9, 0],
       [8, 6, 8],
       [4, 8, 8]])

What does the transpose do?

***Answer:*** Switches the axis'

In [52]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

rand_ints = np.random.randint(0, 10, size=(3, 3))
rand_ints_1 = np.random.randint(0, 10, size=(3, 2))



In [53]:
# Perform a dot product on the two newest arrays you created

rand_ints.dot(rand_ints_1)


array([[ 76,  83],
       [ 96, 135],
       [ 44,  92]])

In [54]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)

rand_ints_2 = np.random.randint(0, 10, size=(4, 3))
rand_ints_3 = np.random.randint(0, 10, size=(4, 3))


In [55]:
# Perform a dot product on the two newest arrays you created

rand_ints_2.dot(rand_ints_3)



ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [56]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

rand_ints_2.dot(rand_ints_3.T)



array([[ 0,  3, 12,  6],
       [ 6, 60, 36, 45],
       [ 0, 11,  4,  4],
       [ 7, 46, 16, 36]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [57]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

rand_ints_4 = np.random.randint(0, 10, size=(5, 3))
rand_ints_5 = np.random.randint(0, 10, size=(5, 3))


In [58]:
# Compare the two arrays with '>'

rand_ints_4 > rand_ints_5


array([[ True, False,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

***Answer:*** Returns an array of booleans, as it performs an element-wise comparison.

In [59]:
# Compare the two arrays with '>='

rand_ints_4 >= rand_ints_5


array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True, False, False],
       [False,  True, False]])

In [60]:
# Find which elements of the first array are greater than 7

rand_ints_4 > 7


array([[ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [61]:
# Which parts of each array are equal? (try using '==')

rand_ints_4 == rand_ints_5


array([[False,  True, False],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [63]:
# Sort one of the arrays you just created in ascending order

rand_ints_4.sort()
rand_ints_4


array([[5, 6, 9],
       [3, 6, 7],
       [0, 5, 7],
       [1, 3, 4],
       [0, 5, 5]])

In [64]:
# Sort the indexes of one of the arrays you just created

rand_ints_5.argsort()


array([[2, 1, 0],
       [2, 0, 1],
       [1, 2, 0],
       [0, 2, 1],
       [1, 2, 0]])

In [66]:
# Find the index with the maximum value in one of the arrays you've created

rand_ints_4.argmax()


2

In [74]:
# Find the index with the minimum value in one of the arrays you've created

rand_ints_5.argmin()


13

In [69]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

rand_ints_4.argmax(axis=1)


array([2, 2, 2, 2, 1])

In [75]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created

rand_ints_5.argmin(axis=0)



array([1, 4, 0])

In [76]:
# Create an array of normally distributed random numbers

np.random.randn(1, 5)

array([[ 0.62054822, -0.16093738, -0.3882644 , -0.88551237, -0.35674503]])

In [77]:
# Create an array with 10 evenly spaced numbers between 1 and 100

np.linspace(1, 25, 5)

array([ 1.,  7., 13., 19., 25.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.